<?php

namespace Success\NotificationBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * NotificationLogRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NotificationLogRepository extends EntityRepository
{
}
