<?php

namespace Success\NotificationBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * NotificationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NotificationRepository extends EntityRepository
{
    public function getEmailNotificationsToSend()
    {
        $nowDate = new \DateTime('now');        
        return $this->getEntityManager()->createQuery(
                //"select e from SuccessEventBundle:BaseEvent e where e.startDateTime BETWEEN :start_date AND :end_date ORDER BY e.startDateTime"
                'select e from SuccessNotificationBundle:EmailNotification e where e.startDateTime < :now and e.isSent = false')
                ->setParameter('now', $nowDate->format('Y-m-d H:i:s'))
                ->getResult();
    }
}
