imports:
    - { resource: admin.yml }

parameters:
    success.sales_generator.manager.class: Success\SalesGeneratorBundle\Service\SalesGeneratorManager

services:
    success.sales_generator.manager:
        class: %success.sales_generator.manager.class%
        calls:
             - [setEntityManager, ["@doctrine.orm.entity_manager"]]
             
    sonata.block.service.treeview:
        class: Success\SalesGeneratorBundle\Block\TreeViewBlockService
        tags:
            - { name: sonata.block }
        arguments: [sonata.block.service.treeview, '@templating']
        calls:
             - [setSalesGeneratorManager, ["@success.sales_generator.manager"]]