imports:
    - { resource: config_dev.yml }

doctrine:
    dbal:
        default_connection: default
        connections:
            default:
                driver:   "%database_driver%"
                host:     "%database_host%"
                port:     "%database_port%"
                dbname:   "%database_name%"
                user:     "%database_user%"
                password: "%database_password%"
                charset:  UTF8
#    orm:
#        metadata_cache_driver: apc
#        result_cache_driver: apc
        
framework:
    test: ~
    session:
        storage_id: session.storage.mock_file
    #profiler:
    #    collect: false
    #    only_exceptions: false
    profiler: 
        enabled: true
        #only_exceptions: false 

web_profiler:
    toolbar: true
    intercept_redirects: true

swiftmailer:
    disable_delivery: true
