security:
    encoders:
        Application\Sonata\UserBundle\Entity\User: sha512    
        Success\MemberBundle\Entity\Member: bcrypt

    role_hierarchy:
        ROLE_ADMIN:       [ROLE_USER, ROLE_SONATA_ADMIN]
        ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]
        ROLE_4SPONSOR: [ROLE_USER]
        ROLE_4EDITOR: [ROLE_ADMIN]
        

    acl:
        connection: default

    providers:
        fos_userbundle:
            id: fos_user.user_manager
            
        success_memberbundle:
            entity:
                class: SuccessMemberBundle:Member
                property: externalId
#        success_memberbundle:
#            id: success.member.member_provider

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false
        admin:
            pattern:            /admin(.*)
            context:            user
            form_login:
                provider:       fos_userbundle
                login_path:     /admin/login
                use_forward:    false
                check_path:     /admin/login_check
                failure_path:   null
            logout:
                path:           /admin/logout
            anonymous:          true
            
        4success:
            pattern:             ^/
            form_login:
                provider:       success_memberbundle
            logout:             true
            anonymous:          true


    access_control:

        # Admin login page needs to be access without credential
        - { path: ^/admin/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/logout$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/login_check$, role: IS_AUTHENTICATED_ANONYMOUSLY }

        # Secured part of the site
        # This config requires being logged for the whole site and having the admin role for the admin part.
        # Change these rules to adapt them to your needs
        - { path: ^/admin/, role: [ROLE_ADMIN, ROLE_SONATA_ADMIN] }
        - { path: ^/.*, role: IS_AUTHENTICATED_ANONYMOUSLY }