parameters:
    success_member.member_manager.class: Success\MemberBundle\Service\MemberManager
    memberIdentityPlaceholder: email
    
services:
    success.member.member_manager:
        class: %success_member.member_manager.class%
        arguments: [%memberIdentityPlaceholder%]
        calls:
             - [setEntityManager, ["@doctrine.orm.entity_manager"]]
             - [setPlaceholderManager, ["@success.placeholder.placeholder_manager"]]
             
    success.member.user_manager:
        class: Success\MemberBundle\Service\UserManager
        arguments: [%memberIdentityPlaceholder%]
        calls:
             - [setEntityManager, ["@doctrine.orm.entity_manager"]]
             - [setPlaceholderManager, ["@success.placeholder.placeholder_manager"]]             
             - [setSecurityContext, ["@security.context"]]