parameters:
    success_member.member_manager.class: Success\MemberBundle\Service\MemberManager
    memberIdentityPlaceholder: email
    
services:
    success.member.member_manager:
        class: %success_member.member_manager.class%
        arguments: [%memberIdentityPlaceholder%]
        calls:
             - [setEntityManager, ["@doctrine.orm.entity_manager"]]
             - [setPlaceholderManager, ["@success.placeholder.placeholder_manager"]]
             - [setBonusPricingManager, ["@success.pricing.bonus_pricing_manager"]]
             
    success.member.login_manager:
        class: Success\MemberBundle\Service\MemberLoginManager
        calls:     
             - [setRedisClient, ["@snc_redis.token_client"]]             
             - [setSecurityContext, ["@security.context"]]

    success.member.twig_extension:
        class: Success\MemberBundle\Twig\SuccessMemberExtension
        calls:     
             - [setMemberLoginManager, ["@success.member.login_manager"]]
             - [setMemberManager, ["@success.member.member_manager"]]
             - [setProductPricingManager, ["@success.pricing.product_pricing_manager"]]
        tags:
            - { name: twig.extension }             
             
    success.member.member_provider:
        class: Success\MemberBundle\Security\MemberProvider
        calls:
             - [setEntityManager, ["@doctrine.orm.entity_manager"]]
             
    success.member.tigerr_helper:
        class: Success\MemberBundle\Service\TigerrApiHelper
        arguments: [%tigerr_api_base_url%, %tigerr_api_key%, %tigerr_api_signature%]