parameters:
    success_member.member_manager.class: Success\MemberBundle\Service\MemberManager
    memberIdentityPlaceholder: email
    
services:
    success.member.member_manager:
        class: %success_member.member_manager.class%
        arguments: [%memberIdentityPlaceholder%]
        calls:
             - [setEntityManager, ["@doctrine.orm.entity_manager"]]
             - [setPlaceholderManager, ["@success.placeholder.placeholder_manager"]]

    success.member.member_provider:
        class: Success\MemberBundle\Security\MemberProvider
        calls:
             - [setEntityManager, ["@doctrine.orm.entity_manager"]]
             - [setMemberManager, ["@success.member.member_manager"]]