parameters:
#    success_notification.example.class: Success\NotificationBundle\Example

services:
#    success_notification.example:
#        class: %success_notification.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
