parameters:
    success.notification.base_event_notifier.class: Success\NotificationBundle\Service\BaseEventNotifier

services:
    success.notification.base_event_notifier:
        class: %success.notification.base_event_notifier.class%
#        arguments: [@service_id, "plain_value", %parameter%]

