parameters:
    success.notification.base_event_notifier.class: Success\NotificationBundle\Service\BaseEventNotifier
    success.notification.notification_manager.class: Success\NotificationBundle\Service\NotificationManager

services:
    success.notification.base_event_notifier:
        class: %success.notification.base_event_notifier.class%
        arguments: [@mailer, @success.settings.settings_manager]
        calls: 
            - [setEntityManager, ["@doctrine.orm.entity_manager"]]        

    success.notification.notification_manager:
        class: %success.notification.notification_manager.class%
        arguments: [@success.notification.base_event_notifier]
        calls: 
            - [setEntityManager, ["@doctrine.orm.entity_manager"]]