<?php

namespace Success\EventBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * EventAccessTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EventAccessTypeRepository extends EntityRepository
{
}
