<?php

namespace Success\EventBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * EventRepeatRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EventRepeatRepository extends EntityRepository
{
}
