<?php

namespace Success\PlaceholderBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PlaceholderTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PlaceholderTypeRepository extends EntityRepository
{
}
