services:            
    success.staticpage.page_user_meneger:
        class: Success\StaticPageBundle\Service\PageUserManager
        calls:
            - [setEntityManager, ['@doctrine.orm.entity_manager']]        