services:
    sonata.admin.event_type:
        class: Success\EventBundle\Admin\EventTypeAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "SPONSOR", label: "EventTypes" }
        arguments:
            - ~
            - Success\EventBundle\Entity\EventType
            - ~
            
    sonata.admin.webinar_event:
        class: Success\EventBundle\Admin\WebinarEventAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "SPONSOR", label: "Webinars" }
        arguments:
            - ~
            - Success\EventBundle\Entity\WebinarEvent
            - ~
            
#    sonata.admin.config_homepage:
#        class: Success\EventBundle\Admin\ConfigSuccessAdmin
#        tags:
#            - { name: sonata.admin, manager_type: orm, group: "SPONSOR", label: "Config" }
#        arguments:
#            - ~
#            - Aisel\ConfigBundle\Entity\Config
#            - ~            