services:
    sonata.admin.event_type:
        class: Success\EventBundle\Admin\EventTypeAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "4 Success", label: "EventTypes", show_in_dashboard: false }
        arguments:
            - ~
            - Success\EventBundle\Entity\EventType
            - ~

    sonata.admin.event_access_type:
        class: Success\EventBundle\Admin\EventAccessTypeAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "4 Success", label: "AccessTypes", show_in_dashboard: false }
        arguments:
            - ~
            - Success\EventBundle\Entity\EventAccessType
            - ~
                                    
    sonata.admin.webinar_event:
        class: Success\EventBundle\Admin\WebinarEventAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "4 Success", label: "Webinars" }
        arguments:
            - ~
            - Success\EventBundle\Entity\WebinarEvent
            - ~

    sonata.admin.webinar_signup:
        class: Success\EventBundle\Admin\WebinarSignUpAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "4 Success", label: "Webinar SignsUp" }
        arguments:
            - ~
            - Success\EventBundle\Entity\EventSignUp
            - ~

    sonata.admin.event_repeat:
        class: Success\EventBundle\Admin\EventRepeatAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "4 Success", show_in_dashboard: false  }
        arguments:
            - ~
            - Success\EventBundle\Entity\EventRepeat
            - ~
