parameters:
    success.event.event_manager.class: Success\EventBundle\Service\EventManager

services:
    success.event.event_manager.class:
        class: %success.event.event_manager.class%
#        arguments: [@service_id, "plain_value", %parameter%]
