parameters:
    success.event.event_manager.class: Success\EventBundle\Service\EventManager

services:
    success.event.event_manager:
        class: %success.event.event_manager.class%
#        arguments: [@service_id, "plain_value", %parameter%]
        
    success.event.calendar_event_listener:
        class: Success\EventBundle\EventListener\CalendarEventListener
        arguments: [ @doctrine.orm.entity_manager ]
        tags:
            - {name: kernel.event_listener, event: calendar.load_events, method: loadEvents}
    
    sonata.admin.event_type:
        class: Success\EventBundle\Admin\EventTypeAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "SPONSOR", label: "EventTypes" }
        arguments:
            - ~
            - Success\EventBundle\Entity\EventType
            - ~
            
    sonata.admin.webinar_event:
        class: Success\EventBundle\Admin\WebinarEventAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "SPONSOR", label: "Webinars" }
        arguments:
            - ~
            - Success\EventBundle\Entity\WebinarEvent
            - ~