services:
    sonata.admin.referal_pricing_admin:
        class: Success\PricingBundle\Admin\ReferalPricingAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "4 Success", label: "Реф. выплаты"}
        arguments:
            - ~
            - Success\PricingBundle\Entity\ReferalPricing
            - SuccessPricingBundle:ReferalPricingAdmin
        calls:
            - [setReferalPricingManager, ['@success.pricing.referal_pricing_manager']]
            - [setEntityManager, ['@doctrine.orm.entity_manager']]

    sonata.admin.referal_pricing_value_admin:
        class: Success\PricingBundle\Admin\ReferalPricingValueAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "4 Success", label: "Реферальные выплаты"}
        arguments:
            - ~
            - Success\PricingBundle\Entity\ReferalPricingValue
            - ~
            
    sonata.admin.product_pricing_admin:
        class: Success\PricingBundle\Admin\ProductPricingAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "4 Success", label: "Пакеты"}
        arguments:
            - ~
            - Success\PricingBundle\Entity\ProductPricing
            - ~
            
    sonata.admin.bonus_pricing_admin:
        class: Success\PricingBundle\Admin\BonusPricingAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "4 Success", label: "Бонусы"}
        arguments:
            - ~
            - Success\PricingBundle\Entity\BonusPricing
            - SuccessPricingBundle:BonusPricingAdmin
        calls:
            - [setbonusPricingManager, ['@success.pricing.bonus_pricing_manager']]
            

    sonata.admin.bonus_pricing_value_admin:
        class: Success\PricingBundle\Admin\BonusPricingValueAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "4 Success", label: "Бонусные выплаты"}
        arguments:
            - ~
            - Success\PricingBundle\Entity\BonusPricingValue
            - ~
        calls:
            - [setbonusPricingManager, ['@success.pricing.bonus_pricing_manager']]
            
    sonata.admin.bonus_calculte_shedule_admin:
        class: Success\PricingBundle\Admin\BonusCalculateSheduleAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "4 Success", label: "Начисление бонусов"}
        arguments:
            - ~
            - Success\PricingBundle\Entity\BonusCalculateShedule
            - ~
        calls:
            - [setEntityManager, ['@doctrine.orm.entity_manager']]
        