services:
    sonata.admin.referal_pricing_admin:
        class: Success\PricingBundle\Admin\ReferalPricingAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "4 Success", label: "Реф. выплаты"}
        arguments:
            - ~
            - Success\PricingBundle\Entity\ReferalPricing
            - SuccessPricingBundle:ReferalPricingAdmin
        calls:
            - [setReferalPricingManager, ['@success.pricing.referal_pricing_manager']]
            - [setEntityManager, ['@doctrine.orm.entity_manager']]

    sonata.admin.referal_pricing_value_admin:
        class: Success\PricingBundle\Admin\ReferalPricingValueAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "4 Success", label: "Реферальные выплаты"}
        arguments:
            - ~
            - Success\PricingBundle\Entity\ReferalPricingValue
            - ~
            
    sonata.admin.product_pricing_admin:
        class: Success\PricingBundle\Admin\ProductPricingAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "4 Success", label: "Пакеты"}
        arguments:
            - ~
            - Success\PricingBundle\Entity\ProductPricing
            - ~