services:
    sonata.admin.pricing_admin:
        class: Success\PricingBundle\Admin\PricingAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "4 Success", label: "Pricing"}
        arguments:
            - ~
            - Success\PricingBundle\Entity\Pricing
            - SuccessPricingBundle:PricingAdmin
