imports:
    - { resource: admin.yml }

services:
    success.pricing.pricing_manager:
        class: Success\PricingBundle\Service\PricingManager
        calls:
            - [setEntityManager, ['@doctrine.orm.entity_manager']]