imports:
    - { resource: admin.yml }

services:
    success.pricing.referal_pricing_manager:
        class: Success\PricingBundle\Service\ReferalPricingManager
        calls:
            - [setEntityManager, ['@doctrine.orm.entity_manager']]