imports:
    - { resource: admin.yml }

services:            
    success.pricing.product_pricing_manager:
        class: Success\PricingBundle\Service\ProductPricingManager
        calls:
            - [setEntityManager, ['@doctrine.orm.entity_manager']]            
            - [setAccountManager, ['@success.treasure.account_manager']]
            - [setMemberManager, ['@success.member.member_manager']]
            
    success.pricing.referal_pricing_manager:
        class: Success\PricingBundle\Service\ReferalPricingManager
        calls:
            - [setEntityManager, ['@doctrine.orm.entity_manager']]
            - [setAccountManager, ['@success.treasure.account_manager']]
            - [setMemberManager, ['@success.member.member_manager']]
            
    success.pricing.bonus_pricing_manager:
        class: Success\PricingBundle\Service\BonusPricingManager
        calls:
            - [setEntityManager, ['@doctrine.orm.entity_manager']]
            - [setMemberManager, ['@success.member.member_manager']]            
            
    success.pricing.bonus_calculator:
        class: Success\PricingBundle\Service\BonusCalculator
        calls:
            - [setEntityManager, ['@doctrine.orm.entity_manager']]
            - [setMemberManager, ['@success.member.member_manager']]                        
            - [setBonusPricingManager, ['@success.pricing.bonus_pricing_manager']]
            - [setAccountManager, ['@success.treasure.account_manager']]
            
    success.pricing.twig_extension:
        class: Success\PricingBundle\Twig\SuccessPricingExtension
        calls:     
             - [setBonusCalculator, ["@success.pricing.bonus_calculator"]]
        tags:
            - { name: twig.extension }             
            