services:
    sonata.admin.placeholder_type:
        class: Success\PlaceholderBundle\Admin\PlaceholderTypeAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "4 Success", label: "PlaceholderTypes" }
        arguments:
            - ~
            - Success\PlaceholderBundle\Entity\PlaceholderType
            - ~    
    
    sonata.admin.external_placeholder:
        class: Success\PlaceholderBundle\Admin\ExternalPlaceholderAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "4 Success", label: "Placeholders" }
        arguments:
            - ~
            - Success\PlaceholderBundle\Entity\ExternalPlaceholder
            - ~