parameters:
    success.placeholder.manager.class: Success\PlaceholderBundle\Service\PlaceholderManager

services:
    success.placeholder.manager:
        class: 
        class: %success.placeholder.manager.class%
        #arguments: [@service_id, "plain_value", %parameter%]


    sonata.admin.external_placeholder:
        class: Success\PlaceholderBundle\Admin\ExternalPlaceholderAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "SPONSOR", label: "Placeholders" }
        arguments:
            - ~
            - Success\PlaceholderBundle\Entity\ExternalPlaceholder
            - ~            