parameters:
    success.placeholder.manager.class: Success\PlaceholderBundle\Service\PlaceholderManager

services:
    success.placeholder.manager:
        class: 
        class: %success.placeholder.manager.class%
        #arguments: [@service_id, "plain_value", %parameter%]
