imports:
    - { resource: admin.yml }

parameters:
    success.placeholder.manager.class: Success\PlaceholderBundle\Service\PlaceholderManager

services:
    success.placeholder.placeholder_manager:
        class: %success.placeholder.manager.class%
        calls:
             - [setEntityManager, ["@doctrine.orm.entity_manager"]]
             - [setRequest, ["@?request="]]

        #arguments: ~


#    sonata.admin.external_placeholder:
#        class: Success\PlaceholderBundle\Admin\ExternalPlaceholderAdmin
#        tags:
#            - { name: sonata.admin, manager_type: orm, group: "SPONSOR", label: "Placeholders" }
#        arguments:
#            - ~
#            - Success\PlaceholderBundle\Entity\ExternalPlaceholder
#            - ~            